#include "vtkgeojsonreader.h"

vtkGeoJSONReader::vtkGeoJSONReader()
{
}

bool vtkGeoJSONReader::CanReadFile(const char *filename)
{
    //Check if file can be opened for reading
    file.open(filename);

    if(!file.is_open())
    {
        std::cout << "File Not Opened!";
        return false;
    }
    return true;
}

void vtkGeoJSONReader::SetFileName(const char *fileName)
{
    //Set filename for the source of the geoJSON data
    //Possible Memory problems
    this->fileName = fileName;
}

void vtkGeoJSONReader::Update()
{
    //Read data from the geoJSON file and update outputData with appropriate vtkPolyData generated according to the data in the source file

    if(!CanReadFile(this->fileName))
    {
        std::cout << "Unable to Open File in parseFile " << this->fileName << std::endl;
    }

    Json::Value root;
    Json::Reader reader;

    //parse the entire geoJSON data into the Json::Value root
    bool parsedSuccess = reader.parse(file, root, false);

    if(!parsedSuccess)
    {
        // Report failures and their locations in the document.
        cout<<"Failed to parse JSON" << endl << reader.getFormatedErrorMessages() << endl;
        return;
    }

    //If parsed successfully into Json parser Values and Arrays, then convert it into appropriate vtkPolyData
    if(root.isObject())
    {
        ParseRoot(root);
    }
}

void vtkGeoJSONReader::ParseRoot(Json::Value root)
{
    Json::Value rootType = root.get("type", -1);
    Json::Value rootFeatures = root.get("features", -1);

    if(rootFeatures == -1)
    {
        std::cout << "Parse Root :: Features :: -1" << std::endl;
        return;
    }

    if(rootFeatures.isArray())
    {
        //If it is a collectiion of features

        vtkAppendPolyData *appendPolyDataFilter = vtkAppendPolyData::New();
        for(int i = 0; i < rootFeatures.size(); i++)
        {
            //Obtain vtkPolyData for each individual feature in the feature collection
            //and append it in the vtkAppendPolyData filter
            Json::Value child = rootFeatures[i];
            vtkGeoJSONFeature *feature = new vtkGeoJSONFeature();
            feature->extractGeoJSONFeature(child);
            appendPolyDataFilter->AddInputData(feature->GetOutput());
        }

        //Clean the appended polyData to remove replications
        vtkCleanPolyData *cleanPolyData = vtkCleanPolyData::New();
        cleanPolyData->SetInputConnection(appendPolyDataFilter->GetOutputPort());
        cleanPolyData->Update();

        //Update the outputData from the data generated by parsing and appending the data from multiple features
        this->outputData = cleanPolyData->GetOutput();
    }
    else
    {
        //Single feature in the geoJSON data
        vtkGeoJSONFeature *feature = new vtkGeoJSONFeature();
        feature->extractGeoJSONFeature(rootFeatures);
        outputData = feature->GetOutput();
    }
}

vtkPolyData *vtkGeoJSONReader::GetOutput()
{
    //Return the outputData generated after parsing the data from the geoJSON source file
    return outputData;
}
